version: '3'

services:
  tinyhome:
    container_name: tinyhome-alpine
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./css:/usr/share/nginx/html/css:ro
      - ./img:/usr/share/nginx/html/img:ro
      - ./webfonts:/usr/share/nginx/html/webfonts:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro